receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  zipkin:
    endpoint: ${GRAYLOG_ZIPKIN_ENDPOINT}
    format: proto
  otlp:
    endpoint: ${GRAYLOG_OTLP_EXPORTER_ENDPOINT}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
